## Constructing co-expression graph

In [1]:
import pandas as pd
import numpy as np

_Loading expression data for selected mice._

In [2]:
expression_data_all_features = pd.read_pickle("processed_data/expression_standardized_cleaned.pkl")

In [3]:
expression_data_all_features

strain    Nmt1_10338077_Muscle_CD  Psmb5_10338095_Muscle_CD  \
B6D2F1                        NaN                       NaN   
BXD1                          NaN                       NaN   
BXD100                  -0.725161                  0.007720   
BXD101                  -1.317918                  1.462562   
BXD102                        NaN                       NaN   
...                           ...                       ...   
BXD98                    2.220295                 -1.073020   
BXD99                   -1.305697                  0.207241   
C57BL.6J                -1.929009                 -0.557591   
D2B6F1                        NaN                       NaN   
DBA.2J                  -0.156847                  1.263041   

strain    Hdac5_10338098_Muscle_CD  Dlg1_10338109_Muscle_CD  \
B6D2F1                         NaN                      NaN   
BXD1                           NaN                      NaN   
BXD100                    0.376058                 0.545516   
BXD101                    0.845329                 0.515211   
BXD102                         NaN                      NaN   
...                            ...                      ...   
BXD98                     0.193564                 0.252363   
BXD99                     1.453644                 0.255455   
C57BL.6J                 -0.353919                -0.014195   
D2B6F1                         NaN                      NaN   
DBA.2J                    1.831667                -0.289412   

strain    Wars_10338116_Muscle_CD  Psph_10338122_Muscle_CD  \
B6D2F1                        NaN                      NaN   
BXD1                          NaN                      NaN   
BXD100                  -1.104466                -0.273818   
BXD101                  -1.058281                -0.056781   
BXD102                        NaN                      NaN   
...                           ...                      ...   
BXD98                    1.052343                -1.433933   
BXD99                   -0.748846                 0.607248   
C57BL.6J                 0.050143                -1.273739   
D2B6F1                        NaN                      NaN   
DBA.2J                  -0.166923                 1.565828   

strain    Copa_10338123_Muscle_CD  Tbl3_10338144_Muscle_CD  \
B6D2F1                        NaN                      NaN   
BXD1                          NaN                      NaN   
BXD100                  -0.901318                -0.509151   
BXD101                  -0.942842                -0.953912   
BXD102                        NaN                      NaN   
...                           ...                      ...   
BXD98                   -0.207268                 1.668022   
BXD99                   -0.625478                 1.101311   
C57BL.6J                -0.064899                -0.132540   
D2B6F1                        NaN                      NaN   
DBA.2J                  -0.293283                -0.857069   

strain    Hb1bp3_10338180_Muscle_CD  Aup1_10338221_Muscle_CD  ...  \
B6D2F1                          NaN                      NaN  ...   
BXD1                            NaN                      NaN  ...   
BXD100                    -0.924874                 0.986363  ...   
BXD101                     0.496976                 0.299762  ...   
BXD102                          NaN                      NaN  ...   
...                             ...                      ...  ...   
BXD98                      0.450924                -0.547979  ...   
BXD99                     -1.224210                -0.611035  ...   
C57BL.6J                  -0.677345                 2.506693  ...   
D2B6F1                          NaN                      NaN  ...   
DBA.2J                    -1.396905                 0.467909  ...   

strain    AFFX-r2-P1-cre-3_AFFX-r2-P1-cre-5_at_Eye  \
B6D2F1                                    1.945871   
BXD1                                      0.414755   
BXD10

_As we can observe we have 86 strains (mice) and 1,201,231 expression features._

_Loading the relevant features for our task._

In [4]:
selected_features_df = pd.read_pickle("processed_data/selected_features.pkl")

In [5]:
selected_features = list(selected_features_df.columns)

In [6]:
print('The total number of selected features is {f}'.format(f = len(selected_features)))

The total number of selected features is 54027


_We now select the relevant features for all the available strains._

In [9]:
expression_data = expression_data_all_features[selected_features].T

In [26]:
expression_data.index.name = 'snp'

In [27]:
expression_data

B6D2F1      BXD1    BXD100  \
snp                                                                      
Nmt1_10338077_Muscle_CD                        NaN       NaN -0.725161   
MJ-4000-125_896_ILM104120471_Bone_Femur        NaN -0.198943       NaN   
Mgp_10548879_Amygdala_Female              0.448772  1.193585       NaN   
Gna12_1439206_at_Eye                      1.997524 -0.403447       NaN   
C230029F24Rik_ILM101240504_Bone_Femur          NaN -1.295179       NaN   
...                                            ...       ...       ...   
Slc43a2_1439965_at_Nucleus_accumbens           NaN -0.876296       NaN   
MJ-2000-100_1260_ILM105550215_Bone_Femur       NaN -1.728374       NaN   
9627219_44-S_ILM101940088_Bone_Femur           NaN  0.755028       NaN   
Spry3_ILM100510113_Bone_Femur                  NaN  0.083589       NaN   
Plbd1_10548817_Amygdala_Female           -1.003512  2.304951       NaN   

                                            BXD101    BXD102     BXD11  \
snp                                                                      
Nmt1_10338077_Muscle_CD                  -1.317918       NaN       NaN   
MJ-4000-125_896_ILM104120471_Bone_Femur        NaN       NaN -0.163706   
Mgp_10548879_Amygdala_Female              0.870287  2.797799  1.009428   
Gna12_1439206_at_Eye                           NaN       NaN -0.651824   
C230029F24Rik_ILM101240504_Bone_Femur          NaN       NaN -0.133060   
...                                            ...       ...       ...   
Slc43a2_1439965_at_Nucleus_accumbens           NaN       NaN  0.711479   
MJ-2000-100_1260_ILM105550215_Bone_Femur       NaN       NaN  0.242024   
9627219_44-S_ILM101940088_Bone_Femur           NaN       NaN  0.532840   
Spry3_ILM100510113_Bone_Femur                  NaN       NaN -0.800370   
Plbd1_10548817_Amygdala_Female           -0.432367 -2.124907  0.535794   

                                             BXD12     BXD13     BXD14  \
snp                                                                      
Nmt1_10338077_Muscle_CD                        NaN       NaN       NaN   
MJ-4000-125_896_ILM104120471_Bone_Femur   1.527677 -0.351637  0.376597   
Mgp_10548879_Amygdala_Female             -0.459737       NaN  0.702500   
Gna12_1439206_at_Eye                     -0.557204  0.057823 -0.060451   
C230029F24Rik_ILM101240504_Bone_Femur    -0.990361 -1.209449  0.428948   
...                                            ...       ...       ...   
Slc43a2_1439965_at_Nucleus_accumbens     -0.797622       NaN  0.332415   
MJ-2000-100_1260_ILM105550215_Bone_Femur -0.113743  1.747189  0.816723   
9627219_44-S_ILM101940088_Bone_Femur     -0.002057 -0.158412 -0.240704   
Spry3_ILM100510113_Bone_Femur            -0.318211 -0.731491  0.370588   
Plbd1_10548817_Amygdala_Female           -0.181621       NaN  0.946740   

                                             BXD15  ...      BXD9     BXD90  \
snp                                                 ...                       
Nmt1_10338077_Muscle_CD                        NaN  ...       NaN -0.792381   
MJ-4000-125_896_ILM104120471_Bone_Femur  -0.386874  ... -0.187197       NaN   
Mgp_10548879_Amygdala_Female                   NaN  ...       NaN -0.001390   
Gna12_1439206_at_Eye                      0.105133  ...  0.956709  1.429807   
C230029F24Rik_ILM101240504_Bone_Femur     2.267382  ... -0.161637       NaN   
...                                            ...  ...       ...       ...   
Slc43a2_1439965_at_Nucleus_accumbens      0.203677  ... -1.055099  0.647110   
MJ-2000-100_1260_ILM105550215_Bone_Femur -0.455826  ... -0.127426       NaN   
9627219_44-S_ILM101940088_Bone_Femur      0.903154  ... -1.195290       NaN   
Spry3_ILM100510113_Bone_Femur            -0.019731  ...  0.542788       NaN   
Plbd1_10548817_Amygdala_Female                 NaN  ...       NaN -1.957743   

                                          BXD93  BXD94     BXD95     BXD98  \
snp                                              

_In order to build our co-expression graph, given two SNPs X and Y:_
- _we first obtain the vectors corresponding to the expression for all strains for those SNPS._
- _we then compute the number of common strains for these two SNPs X and Y, call it **n**._
- _we then compute the euclidian distance **e** between the non NaN values of X and Y._
- _we obtain the distance **d** between X and Y by computing d = e / n._

In [14]:
from scipy.spatial.distance import squareform
from scipy.spatial.distance import pdist

_Let's test on 1,000 samples._

In [77]:
samples = expression_data.iloc[:1000]
samples.index.name = 'snp'
samples

B6D2F1      BXD1    BXD100  \
snp                                                                     
Nmt1_10338077_Muscle_CD                       NaN       NaN -0.725161   
MJ-4000-125_896_ILM104120471_Bone_Femur       NaN -0.198943       NaN   
Mgp_10548879_Amygdala_Female             0.448772  1.193585       NaN   
Gna12_1439206_at_Eye                     1.997524 -0.403447       NaN   
C230029F24Rik_ILM101240504_Bone_Femur         NaN -1.295179       NaN   
...                                           ...       ...       ...   
Gmip_10572212_Amygdala_Female           -1.002628 -0.139076       NaN   
Tssk6_10572251_Amygdala_Female           0.997185 -0.038203       NaN   
Garnl3_10481772_Liver_CD                      NaN       NaN  1.181059   
Tmem161a_10572318_Amygdala_Female       -1.123383  1.250064       NaN   
Homer3_10572345_Amygdala_Female         -1.420727 -0.189096       NaN   

                                           BXD101    BXD102     BXD11  \
snp                                                                     
Nmt1_10338077_Muscle_CD                 -1.317918       NaN       NaN   
MJ-4000-125_896_ILM104120471_Bone_Femur       NaN       NaN -0.163706   
Mgp_10548879_Amygdala_Female             0.870287  2.797799  1.009428   
Gna12_1439206_at_Eye                          NaN       NaN -0.651824   
C230029F24Rik_ILM101240504_Bone_Femur         NaN       NaN -0.133060   
...                                           ...       ...       ...   
Gmip_10572212_Amygdala_Female           -0.794451 -1.133703  1.194804   
Tssk6_10572251_Amygdala_Female          -1.809867 -1.587450 -0.636427   
Garnl3_10481772_Liver_CD                -1.582130       NaN       NaN   
Tmem161a_10572318_Amygdala_Female        0.651357  0.234400  1.474579   
Homer3_10572345_Amygdala_Female         -0.704288  0.253647 -0.301794   

                                            BXD12     BXD13     BXD14  \
snp                                                                     
Nmt1_10338077_Muscle_CD                       NaN       NaN       NaN   
MJ-4000-125_896_ILM104120471_Bone_Femur  1.527677 -0.351637  0.376597   
Mgp_10548879_Amygdala_Female            -0.459737       NaN  0.702500   
Gna12_1439206_at_Eye                    -0.557204  0.057823 -0.060451   
C230029F24Rik_ILM101240504_Bone_Femur   -0.990361 -1.209449  0.428948   
...                                           ...       ...       ...   
Gmip_10572212_Amygdala_Female            0.115363       NaN  1.071439   
Tssk6_10572251_Amygdala_Female          -0.897192       NaN -0.506045   
Garnl3_10481772_Liver_CD                      NaN       NaN       NaN   
Tmem161a_10572318_Amygdala_Female       -2.000062       NaN  0.330620   
Homer3_10572345_Amygdala_Female          0.132899       NaN -2.104966   

                                            BXD15  ...      BXD9     BXD90  \
snp                                                ...                       
Nmt1_10338077_Muscle_CD                       NaN  ...       NaN -0.792381   
MJ-4000-125_896_ILM104120471_Bone_Femur -0.386874  ... -0.187197       NaN   
Mgp_10548879_Amygdala_Female                  NaN  ...       NaN -0.001390   
Gna12_1439206_at_Eye                     0.105133  ...  0.956709  1.429807   
C230029F24Rik_ILM101240504_Bone_Femur    2.267382  ... -0.161637       NaN   
...                                           ...  ...       ...       ...   
Gmip_10572212_Amygdala_Female                 NaN  ...       NaN -0.486039   
Tssk6_10572251_Amygdala_Female                NaN  ...       NaN -1.219312   
Garnl3_10481772_Liver_CD                      NaN  ...       NaN -0.886502   
Tmem161a_10572318_Amygdala_Female             NaN  ...       NaN -0.898868   
Homer3_10572345_Amygdala_Female               NaN  ...       NaN -1.646123   

                                         BXD93  BXD94     BXD95     BXD98  \
snp                                                                         
Nmt1_10338077_Muscle_CD 

_Define the distance function that we are using to build the graph._

In [78]:
def distance(u, v):
    # Obtain common indexes that are non NaN for both u and v
    u_valid_indexes = np.argwhere(~np.isnan(u))
    v_valid_indexes = np.argwhere(~np.isnan(v))
    valid_indexes = np.intersect1d(u_valid_indexes, v_valid_indexes)
    
    
    
    # Obtain valid common vectors and length of these vectors
    u_valid = u[valid_indexes]
    v_valid = v[valid_indexes]
    n = len(valid_indexes)
    
    distance = np.linalg.norm(u_valid-v_valid)
    return distance / n 

In [79]:
distances = pd.DataFrame(
    squareform(pdist(samples, distance)),
    columns = samples.index,
    index = samples.index
)

In [80]:
distances

snp                                      Nmt1_10338077_Muscle_CD  \
snp                                                                
Nmt1_10338077_Muscle_CD                                 0.000000   
MJ-4000-125_896_ILM104120471_Bone_Femur                 0.904734   
Mgp_10548879_Amygdala_Female                            0.228011   
Gna12_1439206_at_Eye                                    0.287058   
C230029F24Rik_ILM101240504_Bone_Femur                   1.313537   
...                                                          ...   
Gmip_10572212_Amygdala_Female                           0.195807   
Tssk6_10572251_Amygdala_Female                          0.223247   
Garnl3_10481772_Liver_CD                                0.183333   
Tmem161a_10572318_Amygdala_Female                       0.205330   
Homer3_10572345_Amygdala_Female                         0.184537   

snp                                      MJ-4000-125_896_ILM104120471_Bone_Femur  \
snp                                                                                
Nmt1_10338077_Muscle_CD                                                 0.904734   
MJ-4000-125_896_ILM104120471_Bone_Femur                                 0.000000   
Mgp_10548879_Amygdala_Female                                            0.410771   
Gna12_1439206_at_Eye                                                    0.220498   
C230029F24Rik_ILM101240504_Bone_Femur                                   0.256229   
...                                                                          ...   
Gmip_10572212_Amygdala_Female                                           0.287128   
Tssk6_10572251_Amygdala_Female                                          0.284366   
Garnl3_10481772_Liver_CD                                                0.308084   
Tmem161a_10572318_Amygdala_Female                                       0.333336   
Homer3_10572345_Amygdala_Female                                         0.385587   

snp                                      Mgp_10548879_Amygdala_Female  \
snp                                                                     
Nmt1_10338077_Muscle_CD                                      0.228011   
MJ-4000-125_896_ILM104120471_Bone_Femur                      0.410771   
Mgp_10548879_Amygdala_Female                                 0.000000   
Gna12_1439206_at_Eye                                         0.215914   
C230029F24Rik_ILM101240504_Bone_Femur                        0.355352   
...                                                               ...   
Gmip_10572212_Amygdala_Female                                0.200337   
Tssk6_10572251_Amygdala_Female                               0.204058   
Garnl3_10481772_Liver_CD                                     0.261548   
Tmem161a_10572318_Amygdala_Female                            0.193169   
Homer3_10572345_Amygdala_Female                              0.170327   

snp                                      Gna12_1439206_at_Eye  \
snp                                                             
Nmt1_10338077_Muscle_CD                              0.287058   
MJ-4000-125_896_ILM104120471_Bone_Femur              0.220498   
Mgp_10548879_Amygdala_Female                         0.215914   
Gna12_1439206_at_Eye                                 0.000000   
C230029F24Rik_ILM101240504_Bone_Femur                0.224161   
...                                                       ...   
Gmip_10572212_Amygdala_Female                        0.202688   
Tssk6_10572251_Amygdala_Female                       0.196589   
Garnl3_10481772_Liver_CD                             0.221606   
Tmem161a_10572318_Amygdala_Female                    0.211448   
Homer3_10572345_Amygdala_Female                      0.221845   

snp                                      C230029F24Rik_ILM101240504_Bone_Femur  \
snp                                                                              
Nmt1_10338077_Muscle_CD                                       

In [81]:
distances_matrix = distances.values
print('Matrix containing distances has shape {s}'.format(s = distances_matrix.shape))
distances_matrix

Matrix containing distances has shape (1000, 1000)


array([[0.        , 0.90473373, 0.22801098, ..., 0.18333311, 0.20532999,
        0.18453725],
       [0.90473373, 0.        , 0.4107706 , ..., 0.30808409, 0.33333642,
        0.3855866 ],
       [0.22801098, 0.4107706 , 0.        , ..., 0.26154769, 0.19316939,
        0.17032713],
       ...,
       [0.18333311, 0.30808409, 0.26154769, ..., 0.        , 0.22846186,
        0.22490532],
       [0.20532999, 0.33333642, 0.19316939, ..., 0.22846186, 0.        ,
        0.20179224],
       [0.18453725, 0.3855866 , 0.17032713, ..., 0.22490532, 0.20179224,
        0.        ]])

In [82]:
def epsilon_similarity_graph(distances: np.ndarray, sigma=1, epsilon=0):
    """ distances (n x n): matrix containing the distance between all our data points.
        sigma (float): width of the kernel
        epsilon (float): threshold
        Return:
        adjacency (n x n ndarray): adjacency matrix of the graph.
    """
    W = np.exp(- distances / (2 * sigma ** 2)) # Apply the kernel to the squared distances
    W[W<epsilon] = 0 # Cut off the values below epsilon
    np.fill_diagonal(W, 0) # Remove the connections on the diagonal
    return W

In [83]:
adjacency = epsilon_similarity_graph(distances_matrix)

In [84]:
print(adjacency)

[[0.         0.63612076 0.89225306 ... 0.91240934 0.90242924 0.91186017]
 [0.63612076 0.         0.81433349 ... 0.85723598 0.84648042 0.82465241]
 [0.89225306 0.81433349 0.         ... 0.87741618 0.907933   0.91836206]
 ...
 [0.91240934 0.85723598 0.87741618 ... 0.         0.89205193 0.89363965]
 [0.90242924 0.84648042 0.907933   ... 0.89205193 0.         0.90402694]
 [0.91186017 0.82465241 0.91836206 ... 0.89363965 0.90402694 0.        ]]
